### ISSUE TITLE
Powershell Core 7 support

### ISSUE THREAD

**Issue by silverqx** [NetSPI/PESecurity#22]
Module works fine on PS 5, but when I try it on PS 7 then I get many errors, I'm attaching the output file:
[output.txt](https://github.com/NetSPI/PESecurity/files/7266849/output.txt)

**Comment by eabase** [comment]
Yep, please fix this, or tell us how to work around it. Seem to be an old problem... 

```powershell
InvalidOperation: Method invocation failed because [System.AppDomain] does not 
contain a method named 'DefineDynamicAssembly'.

InvalidOperation: You cannot call a method on a null-valued expression.

...
```

**Comment by egru** [comment]
The work around is to use powershell 5 or lower. I think it needs a large rewrite to work for powershell 7.

**Comment by eabase** [comment]
The following references seem to suggest otherwise:

* https://github.com/dotnet/runtime/issues/27104
* https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Reflection/Emit/AssemblyBuilderAccess.cs
* https://stackoverflow.com/questions/69602204/cannot-create-dynamic-type-in-net-core
* https://stackoverflow.com/questions/37857639/create-a-class-dynamically-using-system-reflection-emit-in-uwp
* https://www.nuget.org/packages/System.Reflection.Emit/
* https://docs.microsoft.com/en-us/dotnet/api/system.reflection?view=dotnet-uwp-10.0&redirectedfrom=MSDN
* https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.definedynamicassembly?view=net-6.0
*

**Comment by egru** [comment]
I'll gladly accept a pull request with the needed changes.

**Comment by eabase** [comment]
@egru 
well that's not gonna happen. I'm obviously not a PS programmer and even less so a .NET fan. 
If I knew how to fix it, you'd have a PR already!

**Comment by egru** [comment]
The latest commit fixes the issue with PowerShell Core.

**Comment by eabase** [comment]
@egru 
Thank you so much Eric, for taking the time for a patch! 💯

**Comment by silverqx** [comment]
Thx @egru I have tested it on PS5 and pwsh core and it works great 👌.
